"""Extract trade data from chart snapshots by re-running the algo at each snapshot hour.

The hourly snapshots are generated by IBDataBridge._on_realtime_bar calling update_plot
at the top of each hour. The chart shows all signals up to that point from the live
tracking CSV data. So we can reconstruct exactly what was on each chart by slicing
the tracking CSV at each hour boundary.

This also reads the actual image files using PIL to extract the stats box text (P/L,
position, signal counts) via OCR if pytesseract is available, or falls back to the
CSV reconstruction.
"""
import pandas as pd
import os, pytz
from TradingAlgoFast import AlgoConfig, run_trading_algo_fast

_EST = pytz.timezone("US/Eastern")

# Load live tracking CSV (this is the data source for the live charts)
live_path = os.path.join(os.path.expanduser("~"), "Desktop", "IB_Live", "tracking",
                         "YM_tracking_DUO158495_2026-06-30_0930.csv")
live = pd.read_csv(live_path, index_col=0, parse_dates=True)

# Chart snapshot directory
_CHART_ROOT = os.path.join(os.path.expanduser("~"), "Desktop", "IB_Live", "charts")

# Snapshot hours
snapshot_hours = ["09:30", "10:00", "11:00", "12:00", "13:00", "14:00", "15:00", "16:00"]

# Try OCR extraction from images
try:
    from PIL import Image
    import pytesseract
    HAS_OCR = True
except ImportError:
    HAS_OCR = False
    print("[INFO] pytesseract not available — using CSV reconstruction only\n")

print("=" * 120)
print("CHART SNAPSHOT EXTRACTION: What was visible on each hourly chart (2026-06-30)")
print("=" * 120)
print()


def extract_from_image(image_path):
    """Try to extract the stats box text from the chart image using OCR."""
    if not HAS_OCR:
        return None
    try:
        img = Image.open(image_path)
        # The stats box is in the right portion of the image (x > 80% width)
        w, h = img.size
        # Crop right side where stats box is
        stats_region = img.crop((int(w * 0.80), 0, w, int(h * 0.5)))
        text = pytesseract.image_to_string(stats_region)
        return text.strip() if text.strip() else None
    except Exception as e:
        return f"[OCR error: {e}]"


def extract_from_csv(cutoff_hour):
    """Reconstruct what the chart showed at this hour from the tracking CSV."""
    cutoff = pd.Timestamp(f"2026-06-30 {cutoff_hour}", tz=_EST)
    sliced = live[live.index <= str(cutoff)]
    if sliced.empty:
        return None

    # Signals up to this point
    signals = sliced[(sliced["signal"].notna()) & (sliced["signal"] != "")]
    buys = signals[signals["signal"].str.upper() == "BUY"]
    sells = signals[signals["signal"].str.upper() == "SELL"]

    # Current state at snapshot time
    last_row = sliced.iloc[-1]
    position = last_row.get("position", "flat")
    session_pl = float(last_row.get("session_pl", 0))
    close_price = float(last_row["Close"])

    # IB state
    ib_position = last_row.get("ib_position", "flat") if "ib_position" in sliced.columns else "flat"
    ib_pl = float(last_row.get("ib_session_pl", 0)) if "ib_session_pl" in sliced.columns else 0

    # Build trade list
    trades = []
    for idx, row in signals.iterrows():
        sig = str(row["signal"]).upper()
        if sig == "SELL":
            price = row.get("sell_price", row["Close"])
        else:
            price = row["Close"]
        if pd.isna(price):
            price = row["Close"]
        trades.append({"time": idx, "signal": sig, "price": float(price)})

    return {
        "cutoff": cutoff_hour,
        "n_bars": len(sliced),
        "n_signals": len(signals),
        "n_buys": len(buys),
        "n_sells": len(sells),
        "position": position,
        "session_pl": session_pl,
        "close": close_price,
        "ib_position": ib_position,
        "ib_pl": ib_pl,
        "trades": trades,
    }


# Process each snapshot
results = []
for hour in snapshot_hours:
    h_int = int(hour.split(":")[0])
    m_int = int(hour.split(":")[1])

    # Check if image exists
    if hour == "09:30":
        img_name = "YM_2026-06-30_0930.jpg"
    else:
        img_name = f"YM_2026-06-30_{h_int:02d}{m_int:02d}_snapshot.jpg"
    img_path = os.path.join(_CHART_ROOT, img_name)
    img_exists = os.path.exists(img_path)

    # Extract from CSV
    csv_data = extract_from_csv(hour)
    if csv_data is None:
        continue

    # Try OCR
    ocr_text = extract_from_image(img_path) if img_exists else None

    results.append({
        "hour": hour,
        "img_exists": img_exists,
        "img_path": img_path,
        "csv_data": csv_data,
        "ocr_text": ocr_text,
    })

# Print results
for r in results:
    d = r["csv_data"]
    print(f"--- {r['hour']} {'[IMAGE EXISTS]' if r['img_exists'] else '[NO IMAGE]'} ---")
    print(f"  Bars: {d['n_bars']}  |  Close: {d['close']:.0f}")
    print(f"  Algo:  pos={d['position']:<6}  P/L={d['session_pl']:+.0f} pts  signals={d['n_signals']} ({d['n_buys']}B {d['n_sells']}S)")
    print(f"  IB:    pos={d['ib_position']:<6}  P/L={d['ib_pl']:+.0f} pts")
    print(f"  Trades on chart:")
    for t in d["trades"]:
        print(f"    {t['time']}  {t['signal']:<5} @ {t['price']:.0f}")
    if r["ocr_text"]:
        print(f"  [OCR from image]: {r['ocr_text'][:100]}")
    print()

# Summary table
print("\n" + "=" * 100)
print("SNAPSHOT SUMMARY TABLE")
print("=" * 100)
print(f"{'Hour':<8} | {'Image':<7} | {'Algo Pos':<10} | {'Algo P/L':<10} | {'IB Pos':<10} | {'IB P/L':<10} | {'Signals':<10} | {'Close':<10}")
print("-" * 100)
for r in results:
    d = r["csv_data"]
    img_str = "YES" if r["img_exists"] else "NO"
    print(f"{d['cutoff']:<8} | {img_str:<7} | {d['position']:<10} | {d['session_pl']:>+8.0f}  | {str(d['ib_position']):<10} | {d['ib_pl']:>+8.0f}  | {d['n_signals']:<10} | {d['close']:<10.0f}")
